<section class="flexwrap">
    <article>
        <h2>Notre adresse</h2>
        <p>Gîte de la Rose de Porcelaine</p>
    	<p>Adeline HONORE</p>
    	<p>Quartier Morne Honoré</p>
    	<p>L'Olivier</p>
        <p>97270 Rivière Pilote</p>
    </article>
    <article>
        <h2>Rejoignez-nous</h2>
        <p>Il n'est pas aisé, notament à la Martinique de trouver facilement une adresse. Voici nos coordonnées GPS ainsi qu'un plan.</p>
        <p>14°31'22.2"N 60°55'16.2"W</p>
        <p>14.522820, -60.921170</p>
    </article>
    <article>
        <h2>Contactez-nous</h2>
        <p><i class="fas fa-phone fa-flip-horizontal"></i> : +33 6 11 65 83 55</p>
    	<address><a href="mailto:honore_adeline@yahoo.fr"><i class="fas fa-paper-plane"></i> : honore_adeline@yahoo.fr</a></address>
    </article>
</section>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d965.5837529584263!2d-60.921717170831435!3d14.522819999365751!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMTTCsDMxJzIyLjIiTiA2MMKwNTUnMTYuMiJX!5e0!3m2!1sfr!2sfr!4v1552931624057" width="100%" height="500" frameborder="0" style="border:0" allowfullscreen></iframe>

