<section>
    <h2>Le gite - <em> le cocon des amoureux</em></h2>
    <p>Le coin des amoureux est composé de :</p>
        <ul>
            <li>1 chambre de 28 m² avec un lit double (160×190) à baldaquin,</li>
            <li>1 salle de bains avec un espace douche, une baignoire et un lavabo,</li>
            <li>WC indépendants.</li>
        </ul>
    
    <table id="galerie_m">
        <tr>
            <td><a href="img/b1.jpg"><img src="img/b1.jpg"></a></td>
            <td><a href="img/b2.jpg"><img src="img/b2.jpg"></a></td>
            <td><a href="img/b3.jpg"><img src="img/b3.jpg"></a></td>
            <td><a href="img/b4.jpg"><img src="img/b4.jpg"></a></td>
        </tr>
        <tr>
            <td><a href="img/b5.jpg"><img src="img/b5.jpg"></a></td>
            <td colspan="2" rowspan="2" ><img src="img/b1.jpg" id="upImag"></td>
            <td><a href="img/b6.jpg"><img src="img/b6.jpg"></a></td>
        </tr>
        <tr>
            <td><a href="img/b7.jpg"><img src="img/b7.jpg"></a></td>
            <td><a href="img/b8.jpg"><img src="img/b8.jpg"></a></td>
        </tr>
        <tr>
            <td><a href="img/b9.jpg"><img src="img/b9.jpg"></a></td>
            <td><a href="img/b10.jpg"><img src="img/b10.jpg"></a></td>
            <td><a href="img/b11.jpg"><img src="img/b11.jpg"></a></td>
            <td><a href="img/b12.jpg"><img src="img/b12.jpg"></a></td>
        </tr>
    </table>
</section>

<section class="caution flexwrap">
    <article>
        <p><i class="fas fa-smoking-ban"></i> Tabac</p>
        <p>Le gîte est <span>non fumeur</span>. Toute personne qui sera surprise fumant dans ces lieux devra en cas de récidive, quitter les lieux.</p>
    </article>
    <article>
        <p><i class="fas fa-paw"></i> Animaux de companie</p>
        <p>Nous acceptons les animaux que sous conditions particulières. Afin de préparer au mieux votre séjour, merci de nous solliciter à ce sujet.</p>
    </article>
    <article>
        <p><i class="fas fa-bug"></i> Insectes</p>
        <p>Nous sommes sur une île des caraïbes, avec un climant tropical. Pensez à vous protéger des piqûres d'insectes(moustiques,...).</p>
    </article>
</section>

