<section>
    <h2>Découvrir l'ile</h2>
    <article>
        <h3>La Martinique</h3>
        <p>La page <a href="https://fr.wikipedia.org/wiki/Martinique" target="_blank"> Wikipedia consacrée à la Martinique</a></p>
    </article>
    <article>
        <h3>Martinique 1°</h3>
        <p>La <a href="https://la1ere.francetvinfo.fr/martinique/" target="_blank">chaine d'info</a></p>
    </article>
    <article>
        <h3>Tombolo</h3>
        <p><a href="https://www.saintemarie-martinique.fr/lilet-sainte-marie-et-son-tombolo.php" target="_blank">L'îlet Sainte Marie et son Tombolo</a></p>
    </article>
    <article>
        <h3>Sources</h3>
        <p>La source chaude et ferrigineuse: <a href="https://www.bellemartinique.com/tourisme/lieux-a-visiter/visites/dlo-ferre-sources-chaudes/" target="_blank">Dlo féré</a></p>
    </article>
</section>