<!--  SLIDER  -->
<div>
	<figure>
		<nav>
			<button id="slider-prev" title="Slide précédante"><i class="fas fa-chevron-left"></i></button>
			<button id="slider-next" title="Slide suivante"><i class="fas fa-chevron-right"></i></button>
		</nav>
		<img src="img/1.jpg" alt="photo 1">
		<aside>
			<p>C’est au cœur de la campagne Pilotine, au Sud de la Martinique,  à 20mn de la plage de l'Anse Figuier que Adeline vous accueille dans son gîte.</p>
			<p>La Rose de Porcelaine vous invite à séjourner en couple, à prendre le temps de vous détendre et à découvrir le terroir martiniquais.</p>
		</aside>
	</figure>
</div>


