<section>
    <h2>La table d'hôtes</h2>
    <article>
        <h3>Les petits-déjeuners</h3>
        <p>Le petit-déjeuner est compris. Il vous sera servi sur plateaux dans votre chambre de 6h30 à 09h00.</p>
        <p>Nous vous proposons :
            <ul>
                <li>Des confitures maison élaborées avec des fruits locaux.</li>
                <li>Des jus de fruits locaux(goyave, fruit de la passion, ...), de l'eau de coco ou du jus de canne à sucre.</li>
                <li>Pains et viennoiseries locaux.</li>
                <li>Miel de producteur local.</li>
                <li>Possibilité de petit-déjeuner salé avec produits de salaison, et œufs au plat.</li>
            </ul>
        </p>
    </article>
    
    <article>
        <h3>Les dîners en table d’hôtes</h3>
        <p>Les dîners autour de notre table d’hôtes sont proposés tous les soirs et sur réservation.</p>
        <p>Votre dîner est composé d’une entrée, d’un plat, d’un dessert (fromage si demandé), apéritif et vin compris.</p>
    </article>
</section>

