<?php if(isAdmin()): ?>
    <section>
        <p>Bonjour <?php echo $_SESSION['a_nom'] ?> <?php echo $_SESSION['a_pnom'] ?></p>
        <p>Que souhatez-vous faire?</p>
        
        <nav>
			<a href="index.php?page=allBookings">Voir la liste des réservations</a>
			<a href="index.php?page=deconnect">Me déconnecter</a>
		</nav>
        </section>
<?php else: ?>
    

    <form method="post" action="index.php?page=loginAdmin">

        <fieldset>
            <p>
                <label for="a_email">E-mail</label><br />
                <input type="text" name="a_email" required />
            </p>
            <p>
                <label for="a_pass">Mot de passe</label>
                <input type="password" name="a_pass" required/>
            </p>
            
            <input type="submit" value="Valider" title="Me connecter en tant qu'administrateur">
            <a class="annuler" href="index.php">Annuler</a>
        </fieldset>
    </form>

<?php endif ?>
        